#!/bin/bash
echo "🚀 Supabase Edge Functions setup..."
echo ""
echo "1. https://supabase.com aç"
echo "2. 'Create a new project' tıkla"
echo "3. Email + password ile signup yap"
echo "4. Project oluştur (Türkiye regional)"
echo "5. Project URL ve Anon Key al"
echo ""
echo "Sonra: bu komutları çalıştır:"
echo ""
echo "npm install -g supabase"
echo "supabase init"
echo "supabase functions deploy scrape-products"
